language: node_js
node_js:
- '8.9'
install:
- yarn
script:
- yarn build
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs -T filename --key /tmp/sftp_rsa sftp://${SFTP_USER}:${SFTP_PASSWORD}@${SFTP_SERVER}/${SFTP_PATH}
